- name:  carete ec2 and r53
  hosts: local
  connection: local
  vars: 
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-0d750c4d0dc1c7758
    zone_id: "Z0398365AXZ3ME1MH9EB"
    domain_name: "daws86s.help"
    instances:
    - mongodb
  tasks:
  - name: create ec2 instance
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

  - name: print public ip adress
    ansible.builtin.debug:
      msg: "{{ item.instances[0].public_ip_address}}"
    loop: "{{ec2_output.results}}"

  - name: print public ip adress
    ansible.builtin.debug:
      msg: "{{ item.instances[0].private_ip_address}}"
    loop: "{{ec2_output.results}}"


  

