- name: cart server
  hosts: cart
  become: yes
  tasks:
  - name: disable nodejs previous version
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable required version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  
  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: system user
      system: true
      shell: /sbin/nologin
      home: /app

  - name: craete app directory
    ansible.builtin.file:
     path: /app
     state: directory

  - name: download the application code
    ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip 
       dest: /tmp/cart.zip

  - name: unzip the file into app directory
    ansible.builtin.unarchive:
      src: /tmp/cart.zip
      dest: /app
      remote_src: yes
  - name: install npm 
    community.general.npm:
      path: /app
  
  - name: Copy cart service file
    ansible.builtin.copy:
      src: cart.service
      dest: /etc/systemd/system/cart.service
  
  - name: start and enable  the service
    ansible.builtin.service:
       name: cart
       enabled: yes 
       state: started
       daemon_reload: true