- name: catalogue server
  hosts: catalogue
  become: yes
  tasks:
  - name: disable nodejs previous version
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: enable required version
    ansible.builtin.command: dnf module enable nodejs:20 -y
  
  - name: install nodejs 
    ansible.builtin.package:
      name: nodejs 
      state: present
  
  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: system user
      system: true
      shell: /sbin/nologin
      home: /app
  # safe to remove the directory, because when we run 2 time it will consider the previously downloaded file though the file have new chnages it doesnot download new one
  - name: remove app directory if exits
    ansible.builtin.file:
      path: /app
      state: absent

  - name: craete app directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: Delete the previously downloaded file
    ansible.builtin.file:
      path: /tmp/catalogue.zip
      state: absent

  - name: download the application code
    ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
       dest: /tmp/catalogue.zip

  - name: unzip the file into app directory
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install npm 
    community.general.npm:
      path: /app
  
  - name: Copy catalogue service file
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: Copy mongo repo file
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: install mongodb client
    ansible.builtin.package:
      name: mongodb-mongosh 
      state: present

  - name: connect to mongodb client
    ansible.builtin.command: mongosh mongodb.daws86s.help --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
    register: catalogue_output 
  
  - name: print catalogue output 
    ansible.builtin.debug:
     msg: "{{ catalogue_output }}"
    
  
  - name: load products in to mongodb
    ansible.builtin.shell: mongosh --host mongodb.daws86s.help </app/db/master-data.js
    when: catalogue_output .stdout | int < 0 

  # - name: reload the service
  #   ansible.builtin.systemd_service:
  #     daemon_reload: true

  - name: start and enable  the service
    ansible.builtin.systemd_service:
       name: catalogue
       enabled: yes 
       state: started
       daemon_reload: true
        

  
  
 

