- name: dispatch server 
  hosts: dispatch
  become: yes
  tasks:
  - name: install golang
    ansible.builtin.package:
      name: golang
      state: present
    
  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: system user
      system: true
      shell: /sbin/nologin
      home: /app
  # safe to remove the directory, because when we run 2 time it will consider the previously downloaded file though the file have new chnages it doesnot download new one
  - name: remove app directory if exits
    ansible.builtin.file:
      path: /app
      state: absent

  - name: craete app directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: Delete the previously downloaded file
    ansible.builtin.file:
      path: /tmp/dispatch.zip
      state: absent

  - name: download the application code
    ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/dispatch-v3.zip 
       dest: /tmp/dispatch.zip

  - name: unzip the file into app directory
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes
  
  - name: install dependencies
    ansible.builtin.command: go mod init dispatch
    args:
      chdir: /app
  - name: install dependencies
    ansible.builtin.command: go get 

  - name: install dependencies
    ansible.builtin.command: go build
  
  - name: Copy dispatch service file
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service
  
  - name: start and enable  the service
    ansible.builtin.systemd_service:
       name: dispatch
       enabled: yes 
       state: started
       daemon_reload: true
