- name: shipping server 
  hosts: shipping
  become: yes
  tasks:
  - name: install maven  and mysql
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - maven
    - mysql
  
  - name: install mysql python libraries
    ansible.builtin.pip:
      executable: pip3.9
      name: PyMySQL

  - name: create system user
    ansible.builtin.user:
      name: roboshop
      comment: system user
      system: true
      shell: /sbin/nologin
      home: /app
  # safe to remove the directory, because when we run 2 time it will consider the previously downloaded file though the file have new chnages it doesnot download new one
  - name: remove app directory if exits
    ansible.builtin.file:
      path: /app
      state: absent

  - name: craete app directory
    ansible.builtin.file:
     path: /app
     state: directory
  
  - name: Delete the previously downloaded file
    ansible.builtin.file:
      path: /tmp/shipping.zip
      state: absent

  - name: download the application code
    ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip 
       dest: /tmp/shipping.zip

  - name: unzip the file into app directory
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename the file name
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar

  - name: Copy shipping service file
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  
  # - name: install mysql client
  #   ansible.builtin.package:
  #     name: mysql 
  #     state: present

   

  - name: import shipping data into mysql
    community.mysql.mysql_db:
      state: import
      name: all
      login_host: mysql.daws86s.help
      login_user: root
      login_password: -pRoboShop@1
      traget: "{{ item }}"
    loop:
    - /app/db/schema.sql
    - /app/db/app-user.sql 
    - /app/db/master-data.sql
    

  
  - name: start and enable  the service
    ansible.builtin.systemd_service:
       name: catalogue
       enabled: yes 
       state: started
       daemon_reload: true
  
  